#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "ParameterIDs.hpp"

#include <cstring>
#include <vector>

// Binary data generated by juce_add_binary_data
#include "BinaryData.h"

//==============================================================================
// URL-to-BinaryData resource mapping
static constexpr struct { const char* url; const char* resourceName; } urlMap[] =
{
    { "index.html",       "index_html" },
    { "js/index.js",      "index_js" },
    { "js/juce/index.js", "index_js2" },
};

//==============================================================================
BasicSynthWebviewAudioProcessorEditor::BasicSynthWebviewAudioProcessorEditor(
    BasicSynthWebviewAudioProcessor& p)
    : AudioProcessorEditor(&p),
      audioProcessor(p),
      // Initialize slider attachments: parameter, relay, undoManager
      osc1DetuneAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::OSC1_DETUNE),
          osc1DetuneRelay, nullptr),
      osc2DetuneAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::OSC2_DETUNE),
          osc2DetuneRelay, nullptr),
      oscMixAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::OSC_MIX),
          oscMixRelay, nullptr),
      noiseLevelAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::NOISE_LEVEL),
          noiseLevelRelay, nullptr),
      filterCutoffAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::FILTER_CUTOFF),
          filterCutoffRelay, nullptr),
      filterResonanceAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::FILTER_RESONANCE),
          filterResonanceRelay, nullptr),
      filterEnvAmountAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::FILTER_ENV_AMOUNT),
          filterEnvAmountRelay, nullptr),
      filterKeytrackAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::FILTER_KEYTRACK),
          filterKeytrackRelay, nullptr),
      attackAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::ATTACK),
          attackRelay, nullptr),
      decayAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::DECAY),
          decayRelay, nullptr),
      sustainAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::SUSTAIN),
          sustainRelay, nullptr),
      releaseAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::RELEASE),
          releaseRelay, nullptr),
      reverbMixAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::REVERB_MIX),
          reverbMixRelay, nullptr),
      reverbSizeAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::REVERB_SIZE),
          reverbSizeRelay, nullptr),
      reverbDecayAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::REVERB_DECAY),
          reverbDecayRelay, nullptr),
      reverbDampingAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::REVERB_DAMPING),
          reverbDampingRelay, nullptr),
      reverbShimmerAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::REVERB_SHIMMER),
          reverbShimmerRelay, nullptr),
      volumeAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::VOLUME),
          volumeRelay, nullptr),
      // Initialize combo box attachments
      osc1WaveformAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::OSC1_WAVEFORM),
          osc1WaveformRelay, nullptr),
      osc2WaveformAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::OSC2_WAVEFORM),
          osc2WaveformRelay, nullptr),
      voiceModeAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::VOICE_MODE),
          voiceModeRelay, nullptr),
      polyphonyAttachment(
          *audioProcessor.apvts.getParameter(ParameterIDs::POLYPHONY),
          polyphonyRelay, nullptr)
{
    // Create WebBrowserComponent with all relays (BEFORE setSize, or setSize triggers resized!)
    webView = std::make_unique<juce::WebBrowserComponent>(
        juce::WebBrowserComponent::Options()
            .withNativeIntegrationEnabled()
            // Pass all slider relays
            .withOptionsFrom(osc1DetuneRelay)
            .withOptionsFrom(osc2DetuneRelay)
            .withOptionsFrom(oscMixRelay)
            .withOptionsFrom(noiseLevelRelay)
            .withOptionsFrom(filterCutoffRelay)
            .withOptionsFrom(filterResonanceRelay)
            .withOptionsFrom(filterEnvAmountRelay)
            .withOptionsFrom(filterKeytrackRelay)
            .withOptionsFrom(attackRelay)
            .withOptionsFrom(decayRelay)
            .withOptionsFrom(sustainRelay)
            .withOptionsFrom(releaseRelay)
            .withOptionsFrom(reverbMixRelay)
            .withOptionsFrom(reverbSizeRelay)
            .withOptionsFrom(reverbDecayRelay)
            .withOptionsFrom(reverbDampingRelay)
            .withOptionsFrom(reverbShimmerRelay)
            .withOptionsFrom(volumeRelay)
            // Pass all combo box relays
            .withOptionsFrom(osc1WaveformRelay)
            .withOptionsFrom(osc2WaveformRelay)
            .withOptionsFrom(voiceModeRelay)
            .withOptionsFrom(polyphonyRelay)
            // Resource provider
            .withResourceProvider([this](const auto& url) {
                return getResource(url);
            })
    );

    addAndMakeVisible(*webView);
    webView->goToURL(juce::WebBrowserComponent::getResourceProviderRoot());

    // setSize must be called AFTER webView is created, or resized() will crash
    setSize(800, 500);
}

BasicSynthWebviewAudioProcessorEditor::~BasicSynthWebviewAudioProcessorEditor() = default;

//==============================================================================
void BasicSynthWebviewAudioProcessorEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colour(0xFF0B0B12));
}

void BasicSynthWebviewAudioProcessorEditor::resized()
{
    if (webView != nullptr)
        webView->setBounds(getLocalBounds());
}

//==============================================================================
const char* BasicSynthWebviewAudioProcessorEditor::getMimeForExtension(const juce::String& extension)
{
    static const std::unordered_map<juce::String, const char*> mimeMap =
    {
        { { "htm"   },  "text/html"                },
        { { "html"  },  "text/html"                },
        { { "txt"   },  "text/plain"               },
        { { "jpg"   },  "image/jpeg"               },
        { { "jpeg"  },  "image/jpeg"               },
        { { "svg"   },  "image/svg+xml"            },
        { { "ico"   },  "image/vnd.microsoft.icon" },
        { { "json"  },  "application/json"         },
        { { "png"   },  "image/png"                },
        { { "css"   },  "text/css"                 },
        { { "map"   },  "application/json"         },
        { { "js"    },  "text/javascript"          },
        { { "woff2" },  "font/woff2"              }
    };

    if (const auto it = mimeMap.find(extension.toLowerCase()); it != mimeMap.end())
        return it->second;

    jassertfalse;
    return "text/plain";
}

std::optional<juce::WebBrowserComponent::Resource>
BasicSynthWebviewAudioProcessorEditor::getResource(const juce::String& url)
{
    const auto urlToRetrieve = url == "/" ? juce::String{ "index.html" }
                                          : url.fromFirstOccurrenceOf("/", false, false);

    // Look up URL in mapping table
    for (auto& mapping : urlMap)
    {
        if (urlToRetrieve == mapping.url)
        {
            int dataSize = 0;
            const char* data = BinaryData::getNamedResource(mapping.resourceName, dataSize);

            if (data != nullptr && dataSize > 0)
            {
                std::vector<std::byte> result(static_cast<size_t>(dataSize));
                std::memcpy(result.data(), data, static_cast<size_t>(dataSize));
                auto mime = getMimeForExtension(
                    urlToRetrieve.fromLastOccurrenceOf(".", false, false));
                return juce::WebBrowserComponent::Resource{
                    std::move(result), juce::String{ mime }
                };
            }
        }
    }

    return std::nullopt;
}
